### ISSUE TITLE
pxXNA will crash if the 'Configuration' and 'Save' files are not present in the Content folder

### ISSUE THREAD

**Issue by bugswithdrugs** [bugswithdrugs/pxXNA#1]
pxXNA will crash if the 'Configuration' and 'Save' files are not present in the Content folder

**Output Log:**
```
System.IO.DirectoryNotFoundException was unhandled
  HResult=-2147024893
  Message=Could not find a part of the path 'C:\Users\James\Documents\Visual Studio 2010\Projects\pxXNA\pxXNA\pxXNA\bin\x86\Debug\Content\Configuration\Settings.cfg'.
  Source=mscorlib
  StackTrace:
       at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
       at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
       at System.IO.StreamReader..ctor(String path)
       at pxXNA.Game1.load_Settings() in C:\Users\James\Documents\Visual Studio 2010\Projects\pxXNA\pxXNA\pxXNA\Game1.vb:line 1836
       at pxXNA.Game1.Initialize() in C:\Users\James\Documents\Visual Studio 2010\Projects\pxXNA\pxXNA\pxXNA\Game1.vb:line 247
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at pxXNA.Program.Main(String[] args) in C:\Users\James\Documents\Visual Studio 2010\Projects\pxXNA\pxXNA\pxXNA\Program.vb:line 9
  InnerException: 
```

**Solution:**

Find a way for the engine to generate these files if they do not exist.

**Comment by bugswithdrugs** [comment]
[Fixed.](https://github.com/bugswithdrugs/pxXNA/commit/1973786d3edec6f29f59d17f27c8639d8f3cff7e)
